on:
  pull_request: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/test.yml
name: Semgrep Scan
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
    - name: Checkout rules
      uses: actions/checkout@v3
      with:
        repository: shreyashjain06/semgrep-rules
        path: ./rules
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ./code
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Run monitor rules & send results to Defect Dojo, if a PR
      id: run_monitor_rules_pr
      env:
        SEMGREP_RULES: ./../rules/monitor/
      run: |
        cd code;
        echo $(semgrep ci --sarif || true) > monitor_out.sarif;
      if: github.event_name == 'pull_request'
    - name: Run comment rules, retrieve JSON results & send results to Defect Dojo, if a PR.
      id: run_comment_rules_pr
      env:
        SEMGREP_RULES: ./../rules/comment/
      run: |
        cd code;
        echo $(semgrep ci --json || true) > comment_out.json;
        echo $(semgrep ci --sarif || true) > comment_out.sarif;
        if [[ -s comment_out.json ]]; then
          python3 ./../rules/scripts/retrieve-results-from-json.py ./comment_out.json ./comment_results.txt;
          if [[ -s comment_results.txt ]]; then
            echo "::set-output name=comment_results_file_exists::True"
          else
            echo "::set-output name=comment_results_file_exists::False"
          fi
        fi
      if: github.event_name == 'pull_request'
    - name: Rename the comment results file to final results file if that file exists
      id: pr_comment_case1
      run: |
        mv ./code/comment_results.txt ./code/final_results.txt
        sed -i '1s/^/Semgrep SAST Scan Results /' ./code/final_results.txt
        if [[ -s ./code/final_results.txt ]]; then
          echo "::set-output name=final_results_file_exists::True"
        fi
      if: steps.run_comment_rules_pr.outputs.comment_results_file_exists == 'True'
    - name: Create file with no results if comment results file does not exist
      id: pr_comment_case2
      run: |
        echo "Semgrep SAST Scan - Passed. No findings." > ./code/final_results.txt
        if [[ -s ./code/final_results.txt ]]; then
          echo "::set-output name=final_results_file_exists::True"
        fi
      if: steps.run_comment_rules_pr.outputs.comment_results_file_exists == 'False'
    - name: Comment on the PR
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        recreate: true
        path: ./code/final_results.txt
      if: steps.pr_comment_case1.outputs.final_results_file_exists == 'True' || steps.pr_comment_case2.outputs.final_results_file_exists == 'True'

