on:
  pull_request: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/test.yml
name: Semgrep Scan
jobs:
  semg:
    name: Scan
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
    - name: Checkout rules
      uses: actions/checkout@v3
      with:
        repository: shreyashjain06/semgrep-rules
        path: ./rules
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ./code
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: semgrep
      uses: ./share/gh-actions
      with:
        run-semgrep: 1
      env:
        SEMGREP_RULES: p/golang
      if: github.event_name == 'pull_request'
