on:
  pull_request: {}
  push:
    branches:
    - main
    paths:
    - .github/workflows/test.yml
name: test
jobs:
  semg:
    name: Scan
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ./code
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: semgrep
      uses: ./share/test
      with:
        run-semgrep: 1
      env:
        SEMGREP_RULES: p/python
      if: github.event_name == 'pull_request'
